### ISSUE TITLE
Toggle console icon appears automatically

### ISSUE THREAD

**Issue by mbokil** [thiagolucio/toolbar-iconshortcuts#5] opened 2018-03-08 18:36 UTC
Using Atom beta. My toolbar has a Toggle Console icon at the top I am unable to remove. Any suggestions? 
<img width="55" alt="toolbar-iconshortcuts" src="https://user-images.githubusercontent.com/1885868/37169319-9a0e39be-22d5-11e8-8340-4b99bc68a13a.png">

I found a workaround to hide the terminal icon. In styles.less Atom file I added the following:
```
.tool-bar button:first-child {
    display:none;
}
.tool-bar {
    padding-top:5px;
}
```

**Comment by croaker000** [comment] 2018-05-03 09:51
Atom 1.26.1 now has the "Attach Debugger" icon automatically added as well as the "Toggle Console" icon. I don't want either. How can we remove them?

**Comment by thiagolucio** [comment] 2020-04-14 12:54
Hi.
I apologize for the delay. I didn't really receive the warning or at least I don't remember receiving it. Perhaps the problem has already been eliminated.

The problem is not in the package but in the Atom version. Beta packages are not stable and have not been reviewed. The problem is in the compatibility of CoffeeScript that is unable to interpret the toolbar icon package, which is the package that contains this package (dependency). For this reason, there is no way, through my package, to make this change.

My sincere suggestion is that you start using stable packages to avoid this or other problems. But if you want to solve this problem, I recommend that you study a little more about the Suda package.
https://atom.io/packages/tool-bar

I will be closing this ticket but I am available if you have any other problems.

**Closed by thiagolucio** 2020-04-14 12:54 UTC
